// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlK-8ssbhEmijZ_1MWpiSHfm3SmBiu2TI',
    appId: '1:289532294963:web:0a6d8ce3cdbe758aa77046',
    messagingSenderId: '289532294963',
    projectId: 'frut-hub-51e07',
    authDomain: 'frut-hub-51e07.firebaseapp.com',
    storageBucket: 'frut-hub-51e07.firebasestorage.app',
    measurementId: 'G-2GNP3XT02L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNrorDzDwJM8LnZNp1orVWFEqTNvmAo0U',
    appId: '1:289532294963:android:287ffed7eda71251a77046',
    messagingSenderId: '289532294963',
    projectId: 'frut-hub-51e07',
    storageBucket: 'frut-hub-51e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlyxiYhl4Qp6y_vGmyGaAMnWVvSgq30lc',
    appId: '1:289532294963:ios:94f163887a094595a77046',
    messagingSenderId: '289532294963',
    projectId: 'frut-hub-51e07',
    storageBucket: 'frut-hub-51e07.firebasestorage.app',
    iosClientId: '289532294963-c1mdch4rjn9i78gqlq6lg1fv4t81kpnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlyxiYhl4Qp6y_vGmyGaAMnWVvSgq30lc',
    appId: '1:289532294963:ios:94f163887a094595a77046',
    messagingSenderId: '289532294963',
    projectId: 'frut-hub-51e07',
    storageBucket: 'frut-hub-51e07.firebasestorage.app',
    iosClientId: '289532294963-c1mdch4rjn9i78gqlq6lg1fv4t81kpnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXxmlN_0bFSj65iR9gu6v04rFCiQlqnho',
    appId: '1:289532294963:web:1be88bc99ec232eda77046',
    messagingSenderId: '289532294963',
    projectId: 'frut-hub-51e07',
    authDomain: 'frut-hub-51e07.firebaseapp.com',
    storageBucket: 'frut-hub-51e07.firebasestorage.app',
    measurementId: 'G-R04H43ZQ90',
  );
}
